# Generated by Django 5.0.2 on 2024-06-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aianalysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentbasket",
            name="volatility",
            field=models.CharField(max_length=255),
        ),
    ]
