# Generated by Django 5.0.2 on 2024-06-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aianalysis", "0002_alter_investmentbasket_volatility"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentbasket",
            name="basket_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="holding",
            name="asset_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="holding",
            name="distribution_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investmentbasket",
            name="cagr",
            field=models.FloatField(
                blank=True, help_text="Compound Annual Growth Rate", null=True
            ),
        ),
        migrations.AlterField(
            model_name="investmentbasket",
            name="manager_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investmentbasket",
            name="minimum_investment_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="investmentbasket",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="investmentbasket",
            name="volatility",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
