# Generated by Django 5.0.2 on 2024-06-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aianalysis", "0003_investmentbasket_basket_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentbasket",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
